# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['console_app.py'],
    pathex=[],
    binaries=[
        ('.venv/Lib/site-packages/pupil_apriltags/lib/apriltag.dll', 'pupil_apriltags/lib'),
    ],
    datas=[],
    hiddenimports=[
        'pupil_apriltags',
        'pupil_labs.realtime_api',
        'pupil_labs',
        'pupil_labs.realtime_api.models',
        'pupil_labs.realtime_api.streaming',
        'pupil_labs.realtime_api.device',
        'pupil_labs.neon_recording',
        'pupil_labs.neon_recording.calib',
        'numpy',
        'six',
        'websockets',
        'cv2',
        'yaml',
        'pynput',
        'zeroconf',
        'zeroconf._utils.ipaddress',
        'zeroconf._handlers.answers'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'pandas',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
        'setuptools',
        'tkinter',
        'PIL',
        'Pillow',
        'jinja2',
        'pygments',
        'astroid',
        'jedi',
        'parso',
        'wcwidth',
        'sqlite3',
        'zmq',
        'platformdirs',
        'certifi',
        'packaging',
        'pycparser',
        'psutil',
        'pytz',
        'pkg_resources',
        'gi',
        'clr',
        'clr_loader',
        'shelve',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='GazedeckConsole',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='GazedeckConsole',
)
